#!/usr/bin/env python3
"""Inject a phase-colored favicon + Open Graph / Twitter share meta into every
slide deck and the main index.html. Idempotent: re-running replaces the block
between the SOCIAL markers instead of duplicating it.

Run from repo root: python3 scripts/inject_meta.py
"""
import os
import re
import html

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BASE = "https://akmalakhpah.github.io/training-ai-fde"

BEGIN = "  <!-- SOCIAL:BEGIN (generated by scripts/inject_meta.py) -->"
END = "  <!-- SOCIAL:END -->"

PHASE_COLOR = {  # hex without '#'
    "p0": "1856FF", "p1": "1856FF", "p2": "07CA6B", "p3": "F4A52A", "p4": "EA2143",
}
PHASE_NAME = {
    "p0": "Setup", "p1": "Production Engineering Foundations",
    "p2": "AI Application Engineering", "p3": "The FDE Craft",
    "p4": "Capstone Embedded Deployment",
}

# week -> (phaseId, topic, description)
WEEKS = {
    0:  ("p0", "Setup and Diagnostic", "Tooling, accounts, and a working environment before Week 1 of the AI FDE Training."),
    1:  ("p1", "From Coursework to Production", "The production habits that survive contact with a real system."),
    2:  ("p1", "Data Fluency", "Reading, shaping, and trusting real-world data."),
    3:  ("p1", "Deploy, Observe, Recover", "Shipping code and keeping it alive in production."),
    4:  ("p2", "LLM Application Patterns", "Building reliable systems on top of unreliable models."),
    5:  ("p2", "Retrieval and Grounding (RAG)", "Giving models the right context, on demand."),
    6:  ("p2", "MCP and Tool Calling", "Letting models act through real tools."),
    7:  ("p2", "Automation with N8N", "Wiring services into working pipelines."),
    8:  ("p3", "Scoping Ambiguity", "Turning a vague brief into a real plan."),
    9:  ("p3", "Integration and the Messy Real World", "Making it work inside someone else's system."),
    10: ("p3", "Customer-Facing Communication and Capstone Scoping", "Talking to customers and scoping the capstone."),
    11: ("p4", "Build in Place", "A real deployment with a real owner and a real deadline."),
    12: ("p4", "Ship and Defend", "Ship it, then defend the decisions."),
}


def favicon_href(color_hex, label):
    """SVG data-URI: rounded square in the phase color with a label."""
    size, ty = (58, 70) if len(label) <= 1 else (44, 66)
    svg = (
        "<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'>"
        f"<rect width='100' height='100' rx='22' fill='#{color_hex}'/>"
        f"<text x='50' y='{ty}' font-family='monospace' font-size='{size}' "
        f"font-weight='700' fill='white' text-anchor='middle'>{label}</text>"
        "</svg>"
    )
    enc = (svg.replace("<", "%3C").replace(">", "%3E")
              .replace("#", "%23").replace(" ", "%20"))
    return "data:image/svg+xml," + enc


def a(s):
    """Escape for an HTML double-quoted attribute."""
    return html.escape(s, quote=True)


def block(*, favicon, og_type, title, desc, url, image):
    return "\n".join([
        BEGIN,
        f'  <link rel="icon" href="{favicon}" />',
        '  <meta name="description" content="' + a(desc) + '" />',
        '  <meta property="og:type" content="' + og_type + '" />',
        '  <meta property="og:site_name" content="AI FDE Training" />',
        '  <meta property="og:title" content="' + a(title) + '" />',
        '  <meta property="og:description" content="' + a(desc) + '" />',
        '  <meta property="og:url" content="' + url + '" />',
        '  <meta property="og:image" content="' + image + '" />',
        '  <meta property="og:image:type" content="image/png" />',
        '  <meta property="og:image:width" content="1200" />',
        '  <meta property="og:image:height" content="630" />',
        '  <meta property="og:image:alt" content="' + a(title) + '" />',
        '  <meta name="twitter:card" content="summary_large_image" />',
        '  <meta name="twitter:title" content="' + a(title) + '" />',
        '  <meta name="twitter:description" content="' + a(desc) + '" />',
        '  <meta name="twitter:image" content="' + image + '" />',
        END,
    ])


def upsert(path, new_block):
    with open(path, "r", encoding="utf-8") as f:
        src = f.read()
    pat = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END), re.DOTALL)
    if pat.search(src):
        out = pat.sub(new_block, src)
    else:
        out = src.replace("</head>", new_block + "\n</head>", 1)
    with open(path, "w", encoding="utf-8") as f:
        f.write(out)
    print("updated", os.path.relpath(path, ROOT))


def main():
    for n, (pid, topic, desc) in WEEKS.items():
        path = os.path.join(ROOT, "slides", f"week-{n:02d}.html")
        title = f"Week {n} · {topic}"
        blk = block(
            favicon=favicon_href(PHASE_COLOR[pid], str(n)),
            og_type="article",
            title=title,
            desc=desc,
            url=f"{BASE}/slides/week-{n:02d}.html",
            image=f"{BASE}/og/week-{n:02d}.png",
        )
        upsert(path, blk)

    # main page
    home = os.path.join(ROOT, "index.html")
    blk = block(
        favicon=favicon_href(PHASE_COLOR["p1"], "F"),
        og_type="website",
        title="AI FDE Training — 12-Week Course",
        desc="A 12-week hybrid program that turns you, a fresh graduate, into a deployable AI Forward Deployed Engineer.",
        url=f"{BASE}/",
        image=f"{BASE}/og/home.png",
    )
    upsert(home, blk)


if __name__ == "__main__":
    main()
